### ISSUE TITLE
feat : 회원가입페이지 강아지 정보 입력란 추가

### ISSUE THREAD

**Issue by JAESEONGIM** [Zui-Topia/Pet-Topia-React#24]
## 🍀 Description
설명을 작성하세요.

## ✅ Todo
- [ ] 강아지 이름 입력란 추가 ( 특수문자 입력 시 유효성 검사 빨간색 체크 )
- [ ] 강아지 몸무게 입력란 추가 ( 스크롤 선택창 )
- [ ] 강아지 체고 (길이) 입력란 추가 ( 스크롤 선택창 )

## ETC
선택 완료 시 유효성 체크 활성화 필요
