### ISSUE TITLE
feat : 예약 페이지 피그마 구성에 맞게 작성

### ISSUE THREAD

**Issue by EunchanJeong** [Zui-Topia/Pet-Topia-React#54]
## 🍀 Description
예약 페이지를 피그마 구성에 맞게 작성하는 작업

## ✅ Todo
- [ ] Hearder 컴포넌트, BranchSearch 컴포넌트 배치
- [ ] 예약 달력 컴포넌트, 시간 선택 컴포넌트 배치
- [ ] 피그마 구성에 맞게 css 적용
