### ISSUE TITLE
feat : 지도 컴포넌트로 지도 페이지 배치하기 

### ISSUE THREAD

**Issue by ykc0131** [Zui-Topia/Pet-Topia-React#6]
## 🍀 Description
지도 페이지에서 작업한 component 배치시키는 작업

## ✅ Todo
- [x] 메인 지도 배치 
- [x] 층별 버튼 바 배치
- [x] 카테고리 버튼 배치
- [x] 검색칸 배치
